### ISSUE TITLE
Jupyter notebooks: documentation and automatic testing

### ISSUE THREAD

**Issue by tarnold17** [project-pareto/project-pareto#226]
As of this writing (3/15/23) we do not have any Jupyter notebooks that are part of PARETO, but we have several Jupyter notebooks which are in development that we want to bring into the repo by the end of the month. In addition to simply adding these notebooks to the project-pareto repo, we want to do the following:

- [x] Incorporate Jupyter notebooks into the readthedocs in some capacity (this could be as simple as including links in the readthedocs to the relevant GitHub pages with the Jupyter notebooks)
- [ ] Use GitHub actions to automatically test all Jupyter notebooks (it should be sufficient to simply run the Jupyter notebooks to make sure that no exceptions are thrown)

**Comment by lbianchi-lbl** [comment]
Since we have a few solutions that we could use for this, I think the best thing would be to start from a more detailed understanding of the requirements. As a starting point for a more complete discussions, this would include the following information:

- [ ] Examine the set of notebooks that should be covered by this
  - [ ] How many of them are there?
  - [ ] Are there further notebooks planned after the initial set?
  - [ ] What are the typical runtimes?
  - [ ] Do any of the notebooks need any special requirements, such as:
    - [ ] Additional Python dependencies
    - [ ] Other non-Python tools (e.g. solvers)
    - [ ] Environment/platform/OS restrictions (e.g. they only run on Windows)
- [ ] Description of the intended end-to-end workflow
  - [ ] What type of users are expected to use the notebooks?
  - [ ] Are users expected to make persistent changes to the notebooks? Or just use them as "runnable docs"?
  - [ ] Are the notebooks going to be part of live demonstrations, e.g. workshops?
- [ ] Desired level of integration with the documentation, e.g.:
  - [ ] Should the notebooks be hosted in ReadTheDocs? If so, should they look like the rest of the documentation?

**Comment by ksbeattie** [comment]
Related to #219 in that it will bring in a few notebooks.

**Comment by ksbeattie** [comment]
Once #246 is in, @tarnold17, @lbianchi-lbl and I will meet to discuss how to proceed on this.

**Comment by ksbeattie** [comment]
There's 3 things to be done to close this:
- [x] Get (at least some) of the notebooks added: #219
- [ ] Update the documentation on them 
- [ ] Get some automated testing in place for them

**Comment by ksbeattie** [comment]
The general topic of if these notebooks will be tested withing the IDAES repo will be brought up during the upcoming Oct meeting.  After that, we'll review this issue.
